project:
  type: website

website:
  title: "Eric Peter Wairagala"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
    right:
      - text: "CV"
        icon: file-earmark-pdf
        href: "Eric_Peter_Wairagala_CV.pdf"
  favicon: "images/favicon-32x32.png"
  page-footer:
    center: "© 2024 Eric Peter Wairagala"

format:
  html:
    theme: flatly
    css: styles.css
    toc: false

editor: visual

execute:
  freeze: auto
